# Site settings
title: The Lost Bread
email: your-email@domain.com
url: https://example.github.io
description: "French Toast and Milk Shakes."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: FFF #80B3FF
  secondary: 262626 #FD6E8A
  secondary-dark: 262626 #A2122F

# Footer settings
footer:
  copyright: The Lost Bread
  location: Location
  social: Follow Us
  phone: Phone

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/thelostbread
  - title: instagram
    url: http://instagram.com/thelostbread_
  

# Postal address (add as many lines as necessary)
address:
  - line: 91 Maginhawa St. UP Village
  - line: Quezon City, Philippines

# Credits content
phone: '+63917 821 2111.'

# Build settings
markdown: kramdown
permalink: pretty
